using Microsoft.OpenApi.Models;
using System.Reflection;
using YoutubeToMp3Niraj.Common;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.

builder.Services.AddControllers();
// Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
builder.Services.AddEndpointsApiExplorer();

builder.Services.AddControllersWithViews(options =>
{
    options.Filters.Add<MyActionFilters>();
});

builder.Services.AddSwaggerGen(c =>
{
    //c.SwaggerDoc("v1", new OpenApiInfo { Title = "Youtube to mp3", Version = "v1" });
    //c.IncludeXmlComments(Path.Combine(System.AppContext.BaseDirectory, "YoutubeToMp3Niraj.xml"));
    c.DescribeAllParametersInCamelCase();
    c.SwaggerDoc("v1", new OpenApiInfo
    {
        Title = "Youtube to Mp3 Convreter",
        Version = "v1",
        Description = "This Web API returns mp3 audio from youtube video link [:: Developed by- Niraj Soni ::]",
    });

    //Locate the XML file being generated by ASP.NET...
    var xmlFile = $"{Assembly.GetExecutingAssembly().GetName().Name}.XML";
    var xmlPath = Path.Combine(AppContext.BaseDirectory, xmlFile);

    //... and tell Swagger to use those XML comments.
    c.IncludeXmlComments(xmlPath);
});


var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseHttpsRedirection();

app.UseAuthorization();

app.UseCors(builder => builder
       .AllowAnyHeader()
       .AllowAnyMethod()
       .AllowAnyOrigin().WithExposedHeaders("Content-Disposition")
    );

app.MapControllers();

app.Run();
